  spring:
    profiles: 
      active: "\"cloud\""
    config:
      name: "\"configserver\""
    cloud:
      config:
        server:
          git:
            uri: "\"https://github.com/VenkteshV/microservices-config.repo.git\""
            force-pull: true
  server:
    port: 8888
  management:
    endpoints:
      web:
        exposure:
          include: "*"

          #spring.config.name="configserver"
#server.port=8888
##spring.profiles.active=cloud
#spring.cloud.config.server.git.uri="https://github.com/VenkteshV/microservices-config.repo.git"
#spring.cloud.config.server.git.clone-on-start=true
#spring.cloud.config.server.git.username="VenkteshV"
#spring.cloud.config.server.git.password="Venkycrs1996?"
#spring.cloud.config.server.git.force-pull=true
##spring.cloud.config.server.git.basedir:target/config
#management.endpoints.web.exposure.include=*